version: '3'
services:

    nginx:
        container_name: test-nginx
        build:
            context: ./docker/images/nginx
        restart: always
        ports:
            - 83:80
        links:
            - php-fpm:php
        networks:
            - app_subnet
        volumes:
            - ./symfony:/symfony

    php-fpm:
        container_name: test-php
        build:
            context: ./docker/images/php-fpm
            args:
                - INSTALL_XDEBUG=true
                - XDEBUG_REMOTE_HOST=172.22.0.1
                - XDEBUG_REMOTE_PORT=9000
                - XDEBUG_IDE_KEY=total
        restart: always
        networks:
            - app_subnet
        volumes:
            - ./symfony:/symfony
            - ./docker/volumes/php-fpm/var/log:/var/log
        env_file:
            - symfony/.env

networks:
    app_subnet:
        external: true
